name: sensoresall
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^6.1.0
  intl: ^0.19.0
  path_provider: ^2.0.11
  csv: ^5.0.0
  open_filex: ^4.0.0
  flutter_tts: ^3.6.4  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
